# Makefile.in generated by automake 1.15 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2014 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/dyngb
pkgincludedir = $(includedir)/dyngb
pkglibdir = $(libdir)/dyngb
pkglibexecdir = $(libexecdir)/dyngb
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = test_monomials$(EXEEXT) test_hilbert_functions$(EXEEXT) \
	test_incremental_betti$(EXEEXT) test_glpk_solver$(EXEEXT) \
	test_gmp$(EXEEXT) test_cyclicn$(EXEEXT) test_dynamic$(EXEEXT) \
	test_initial_analysis$(EXEEXT) user_interface$(EXEEXT) \
	test_4by4$(EXEEXT) test_cab_es1$(EXEEXT) test_cab_es2$(EXEEXT) \
	test_cab_es4$(EXEEXT) test_cab_es5$(EXEEXT) \
	test_cab_es6$(EXEEXT) test_cab_es9$(EXEEXT) test_f4$(EXEEXT) \
	test_f4_dynamic$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/ac_checking_ppl.m4 \
	$(top_srcdir)/ac_checking_gmp.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__objects_1 = algorithm_buchberger_dynamic.$(OBJEXT) \
	dynamic_engine.$(OBJEXT)
am__objects_2 = hilbert_functions.$(OBJEXT) \
	dense_univariate_rational_poly.$(OBJEXT) \
	dense_univariate_integer_poly.$(OBJEXT)
am__objects_3 = lp_solver.$(OBJEXT) skeleton.$(OBJEXT) \
	glpk_solver.$(OBJEXT) ppl_solver.$(OBJEXT)
am__objects_4 = monomial_ordering.$(OBJEXT) \
	particular_orderings.$(OBJEXT)
am__objects_5 = monomial.$(OBJEXT) indeterminate.$(OBJEXT)
am__objects_6 = fields.$(OBJEXT) polynomial_ring.$(OBJEXT) \
	polynomial.$(OBJEXT) polynomial_array.$(OBJEXT) \
	polynomial_double_buffered.$(OBJEXT) \
	polynomial_geobucket.$(OBJEXT) \
	polynomial_linked_list.$(OBJEXT)
am__objects_7 = reduction_support.$(OBJEXT)
am__objects_8 = algorithm_buchberger_basic.$(OBJEXT) \
	critical_pair.$(OBJEXT)
am__objects_9 = strategies.$(OBJEXT) sugar_strategy.$(OBJEXT) \
	normal_strategy.$(OBJEXT) weighted_sugar_strategy.$(OBJEXT)
am__objects_10 = $(am__objects_1) $(am__objects_2) $(am__objects_3) \
	$(am__objects_4) $(am__objects_5) $(am__objects_6) \
	$(am__objects_7) $(am__objects_8) $(am__objects_9) \
	monomial_ideal.$(OBJEXT) betti.$(OBJEXT)
am_test_4by4_OBJECTS = test_4by4.$(OBJEXT) $(am__objects_10)
test_4by4_OBJECTS = $(am_test_4by4_OBJECTS)
test_4by4_LDADD = $(LDADD)
test_4by4_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_4by4_LDFLAGS) $(LDFLAGS) -o $@
am_test_cab_es1_OBJECTS = test_cab_es1.$(OBJEXT) $(am__objects_10)
test_cab_es1_OBJECTS = $(am_test_cab_es1_OBJECTS)
test_cab_es1_LDADD = $(LDADD)
test_cab_es1_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_cab_es1_LDFLAGS) $(LDFLAGS) -o $@
am_test_cab_es2_OBJECTS = test_cab_es2.$(OBJEXT) $(am__objects_10)
test_cab_es2_OBJECTS = $(am_test_cab_es2_OBJECTS)
test_cab_es2_LDADD = $(LDADD)
test_cab_es2_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_cab_es2_LDFLAGS) $(LDFLAGS) -o $@
am_test_cab_es4_OBJECTS = test_cab_es4.$(OBJEXT) $(am__objects_10)
test_cab_es4_OBJECTS = $(am_test_cab_es4_OBJECTS)
test_cab_es4_LDADD = $(LDADD)
test_cab_es4_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_cab_es4_LDFLAGS) $(LDFLAGS) -o $@
am_test_cab_es5_OBJECTS = test_cab_es5.$(OBJEXT) $(am__objects_10)
test_cab_es5_OBJECTS = $(am_test_cab_es5_OBJECTS)
test_cab_es5_LDADD = $(LDADD)
test_cab_es5_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_cab_es5_LDFLAGS) $(LDFLAGS) -o $@
am_test_cab_es6_OBJECTS = test_cab_es6.$(OBJEXT) $(am__objects_10)
test_cab_es6_OBJECTS = $(am_test_cab_es6_OBJECTS)
test_cab_es6_LDADD = $(LDADD)
test_cab_es6_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_cab_es6_LDFLAGS) $(LDFLAGS) -o $@
am_test_cab_es9_OBJECTS = test_cab_es9.$(OBJEXT) $(am__objects_10)
test_cab_es9_OBJECTS = $(am_test_cab_es9_OBJECTS)
test_cab_es9_LDADD = $(LDADD)
test_cab_es9_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_cab_es9_LDFLAGS) $(LDFLAGS) -o $@
am_test_cyclicn_OBJECTS = test_cyclicn.$(OBJEXT) $(am__objects_2) \
	$(am__objects_4) $(am__objects_5) $(am__objects_6) \
	$(am__objects_7) $(am__objects_8) $(am__objects_9) \
	algorithm_buchberger_explorer_serial.$(OBJEXT) \
	f4_reduction.$(OBJEXT) monomial_ideal.$(OBJEXT)
test_cyclicn_OBJECTS = $(am_test_cyclicn_OBJECTS)
test_cyclicn_LDADD = $(LDADD)
test_cyclicn_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_cyclicn_LDFLAGS) $(LDFLAGS) -o $@
am_test_dynamic_OBJECTS = test_dynamic.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) $(am__objects_3) $(am__objects_4) \
	$(am__objects_5) $(am__objects_6) $(am__objects_7) \
	$(am__objects_8) $(am__objects_9) monomial_ideal.$(OBJEXT) \
	betti.$(OBJEXT)
test_dynamic_OBJECTS = $(am_test_dynamic_OBJECTS)
test_dynamic_LDADD = $(LDADD)
test_dynamic_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_dynamic_LDFLAGS) $(LDFLAGS) -o $@
am_test_f4_OBJECTS = test_f4.$(OBJEXT) $(am__objects_2) \
	$(am__objects_4) $(am__objects_5) $(am__objects_6) \
	$(am__objects_7) $(am__objects_8) $(am__objects_9) \
	f4_reduction.$(OBJEXT) monomial_ideal.$(OBJEXT)
test_f4_OBJECTS = $(am_test_f4_OBJECTS)
test_f4_LDADD = $(LDADD)
test_f4_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(test_f4_LDFLAGS) \
	$(LDFLAGS) -o $@
am_test_f4_dynamic_OBJECTS = test_f4_dynamic.$(OBJEXT) \
	$(am__objects_1) $(am__objects_2) $(am__objects_3) \
	$(am__objects_4) $(am__objects_5) $(am__objects_6) \
	$(am__objects_7) $(am__objects_8) $(am__objects_9) \
	f4_dynamic.$(OBJEXT) monomial_ideal.$(OBJEXT) betti.$(OBJEXT)
test_f4_dynamic_OBJECTS = $(am_test_f4_dynamic_OBJECTS)
test_f4_dynamic_LDADD = $(LDADD)
test_f4_dynamic_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_f4_dynamic_LDFLAGS) $(LDFLAGS) -o $@
am_test_glpk_solver_OBJECTS = test_glpk_solver.$(OBJEXT) \
	$(am__objects_3) $(am__objects_5) $(am__objects_4)
test_glpk_solver_OBJECTS = $(am_test_glpk_solver_OBJECTS)
test_glpk_solver_LDADD = $(LDADD)
test_glpk_solver_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_glpk_solver_LDFLAGS) $(LDFLAGS) -o $@
am_test_gmp_OBJECTS = test_gmp.$(OBJEXT)
test_gmp_OBJECTS = $(am_test_gmp_OBJECTS)
test_gmp_LDADD = $(LDADD)
test_gmp_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_gmp_LDFLAGS) $(LDFLAGS) -o $@
am_test_hilbert_functions_OBJECTS = test_hilbert_functions.$(OBJEXT) \
	$(am__objects_2) $(am__objects_5) $(am__objects_4) \
	polynomial_linked_list.$(OBJEXT) polynomial.$(OBJEXT) \
	fields.$(OBJEXT) monomial_ideal.$(OBJEXT)
test_hilbert_functions_OBJECTS = $(am_test_hilbert_functions_OBJECTS)
test_hilbert_functions_LDADD = $(LDADD)
test_hilbert_functions_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_hilbert_functions_LDFLAGS) $(LDFLAGS) -o $@
am_test_incremental_betti_OBJECTS = test_incremental_betti.$(OBJEXT) \
	$(am__objects_5) $(am__objects_4) betti.$(OBJEXT)
test_incremental_betti_OBJECTS = $(am_test_incremental_betti_OBJECTS)
test_incremental_betti_LDADD = $(LDADD)
am_test_initial_analysis_OBJECTS = test_initial_analysis.$(OBJEXT) \
	$(am__objects_10)
test_initial_analysis_OBJECTS = $(am_test_initial_analysis_OBJECTS)
test_initial_analysis_LDADD = $(LDADD)
test_initial_analysis_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(test_initial_analysis_LDFLAGS) $(LDFLAGS) -o $@
am_test_monomials_OBJECTS = test_monomials.$(OBJEXT) \
	polynomial_ring.$(OBJEXT) fields.$(OBJEXT) $(am__objects_5) \
	$(am__objects_4)
test_monomials_OBJECTS = $(am_test_monomials_OBJECTS)
test_monomials_LDADD = $(LDADD)
am_user_interface_OBJECTS = user_interface.$(OBJEXT) $(am__objects_10)
user_interface_OBJECTS = $(am_user_interface_OBJECTS)
user_interface_LDADD = $(LDADD)
user_interface_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) \
	$(user_interface_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(test_4by4_SOURCES) $(test_cab_es1_SOURCES) \
	$(test_cab_es2_SOURCES) $(test_cab_es4_SOURCES) \
	$(test_cab_es5_SOURCES) $(test_cab_es6_SOURCES) \
	$(test_cab_es9_SOURCES) $(test_cyclicn_SOURCES) \
	$(test_dynamic_SOURCES) $(test_f4_SOURCES) \
	$(test_f4_dynamic_SOURCES) $(test_glpk_solver_SOURCES) \
	$(test_gmp_SOURCES) $(test_hilbert_functions_SOURCES) \
	$(test_incremental_betti_SOURCES) \
	$(test_initial_analysis_SOURCES) $(test_monomials_SOURCES) \
	$(user_interface_SOURCES)
DIST_SOURCES = $(test_4by4_SOURCES) $(test_cab_es1_SOURCES) \
	$(test_cab_es2_SOURCES) $(test_cab_es4_SOURCES) \
	$(test_cab_es5_SOURCES) $(test_cab_es6_SOURCES) \
	$(test_cab_es9_SOURCES) $(test_cyclicn_SOURCES) \
	$(test_dynamic_SOURCES) $(test_f4_SOURCES) \
	$(test_f4_dynamic_SOURCES) $(test_glpk_solver_SOURCES) \
	$(test_gmp_SOURCES) $(test_hilbert_functions_SOURCES) \
	$(test_incremental_betti_SOURCES) \
	$(test_initial_analysis_SOURCES) $(test_monomials_SOURCES) \
	$(user_interface_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/config.h.in compile \
	depcomp install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/cantanima/common/c++/gbproject/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /home/cantanima/common/c++/gbproject/missing autoconf
AUTOHEADER = ${SHELL} /home/cantanima/common/c++/gbproject/missing autoheader
AUTOMAKE = ${SHELL} /home/cantanima/common/c++/gbproject/missing automake-1.15
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lglpk  -lppl
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/cantanima/common/c++/gbproject/missing makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = dyngb
PACKAGE_BUGREPORT = john.perry@usm.edu
PACKAGE_NAME = dyngb
PACKAGE_STRING = dyngb 2.0
PACKAGE_TARNAME = dyngb
PACKAGE_URL = 
PACKAGE_VERSION = 2.0
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 2.0
abs_builddir = /home/cantanima/common/c++/gbproject
abs_srcdir = /home/cantanima/common/c++/gbproject
abs_top_builddir = /home/cantanima/common/c++/gbproject
abs_top_srcdir = /home/cantanima/common/c++/gbproject
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/cantanima/common/c++/gbproject/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
DYNAMIC_LIB = algorithm_buchberger_dynamic.cpp dynamic_engine.cpp
HILBERT_LIB = hilbert_functions.cpp dense_univariate_rational_poly.cpp dense_univariate_integer_poly.cpp
LP_SOLVERS_LIB = lp_solver.cpp skeleton.cpp glpk_solver.cpp ppl_solver.cpp
MONOMIAL_LIB = monomial.cpp indeterminate.cpp
ORDERING_LIB = monomial_ordering.cpp particular_orderings.cpp
POLY_LIB = fields.cpp polynomial_ring.cpp polynomial.cpp polynomial_array.cpp polynomial_double_buffered.cpp polynomial_geobucket.cpp polynomial_linked_list.cpp
REDUCTION_LIB = reduction_support.cpp
STATIC_LIB = algorithm_buchberger_basic.cpp critical_pair.cpp
STRAT_LIB = strategies.cpp sugar_strategy.cpp normal_strategy.cpp weighted_sugar_strategy.cpp
ALL_DYNAMIC_LIBS = $(DYNAMIC_LIB) $(HILBERT_LIB) $(LP_SOLVERS_LIB) $(ORDERING_LIB) $(MONOMIAL_LIB) $(POLY_LIB) $(REDUCTION_LIB) $(STATIC_LIB) $(STRAT_LIB) monomial_ideal.cpp betti.cpp
GMP_LINK = -lgmpxx -lgmp
DYNAMIC_LINK = $(GMP_LINK) -lppl -lglpk
PARALLEL_LINK = -lpthread -pthread
test_monomials_SOURCES = test_monomials.cpp polynomial_ring.cpp fields.cpp $(MONOMIAL_LIB) $(ORDERING_LIB)
test_hilbert_functions_SOURCES = test_hilbert_functions.cpp $(HILBERT_LIB) $(MONOMIAL_LIB) $(ORDERING_LIB) polynomial_linked_list.cpp polynomial.cpp fields.cpp monomial_ideal.cpp
test_hilbert_functions_LDFLAGS = $(GMP_LINK)
test_incremental_betti_SOURCES = test_incremental_betti.cpp $(MONOMIAL_LIB) $(ORDERING_LIB) betti.cpp
test_glpk_solver_SOURCES = test_glpk_solver.cpp $(LP_SOLVERS_LIB) $(MONOMIAL_LIB) $(ORDERING_LIB)
test_glpk_solver_LDFLAGS = $(DYNAMIC_LINK)
test_gmp_SOURCES = test_gmp.cpp
test_gmp_LDFLAGS = $(GMP_LINK)
test_cyclicn_SOURCES = test_cyclicn.cpp $(HILBERT_LIB) $(ORDERING_LIB) $(MONOMIAL_LIB) $(POLY_LIB) $(REDUCTION_LIB) $(STATIC_LIB) $(STRAT_LIB) algorithm_buchberger_explorer_serial.cpp f4_reduction.cpp monomial_ideal.cpp
test_cyclicn_LDFLAGS = $(GMP_LINK) $(PARALLEL_LINK)
test_dynamic_SOURCES = test_dynamic.cpp $(DYNAMIC_LIB) $(HILBERT_LIB) $(LP_SOLVERS_LIB) $(ORDERING_LIB) $(MONOMIAL_LIB) $(POLY_LIB) $(REDUCTION_LIB) $(STATIC_LIB) $(STRAT_LIB) monomial_ideal.cpp betti.cpp
test_dynamic_LDFLAGS = $(DYNAMIC_LINK)
test_initial_analysis_SOURCES = test_initial_analysis.cpp $(ALL_DYNAMIC_LIBS)
test_initial_analysis_LDFLAGS = $(DYNAMIC_LINK)
user_interface_SOURCES = user_interface.cpp $(ALL_DYNAMIC_LIBS)
user_interface_LDFLAGS = $(DYNAMIC_LINK)
test_4by4_SOURCES = test_4by4.cpp $(ALL_DYNAMIC_LIBS)
test_4by4_LDFLAGS = $(DYNAMIC_LINK)
test_cab_es1_SOURCES = test_cab_es1.cpp $(ALL_DYNAMIC_LIBS)
test_cab_es1_LDFLAGS = $(DYNAMIC_LINK)
test_cab_es2_SOURCES = test_cab_es2.cpp $(ALL_DYNAMIC_LIBS)
test_cab_es2_LDFLAGS = $(DYNAMIC_LINK)
test_cab_es4_SOURCES = test_cab_es4.cpp $(ALL_DYNAMIC_LIBS)
test_cab_es4_LDFLAGS = $(DYNAMIC_LINK)
test_cab_es5_SOURCES = test_cab_es5.cpp $(ALL_DYNAMIC_LIBS)
test_cab_es5_LDFLAGS = $(DYNAMIC_LINK)
test_cab_es6_SOURCES = test_cab_es6.cpp $(ALL_DYNAMIC_LIBS)
test_cab_es6_LDFLAGS = $(DYNAMIC_LINK)
test_cab_es9_SOURCES = test_cab_es9.cpp $(ALL_DYNAMIC_LIBS)
test_cab_es9_LDFLAGS = $(DYNAMIC_LINK)
test_f4_SOURCES = test_f4.cpp $(HILBERT_LIB) $(ORDERING_LIB) $(MONOMIAL_LIB) $(POLY_LIB) $(REDUCTION_LIB) $(STATIC_LIB) $(STRAT_LIB) f4_reduction.cpp monomial_ideal.cpp
test_f4_LDFLAGS = $(GMP_LINK) $(PARALLEL_LINK)
test_f4_dynamic_SOURCES = test_f4_dynamic.cpp  $(DYNAMIC_LIB) $(HILBERT_LIB) $(LP_SOLVERS_LIB) $(ORDERING_LIB) $(MONOMIAL_LIB) $(POLY_LIB) $(REDUCTION_LIB) $(STATIC_LIB) $(STRAT_LIB) f4_dynamic.cpp monomial_ideal.cpp betti.cpp
test_f4_dynamic_LDFLAGS = $(DYNAMIC_LINK) $(GMP_LINK) $(PARALLEL_LINK)
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

test_4by4$(EXEEXT): $(test_4by4_OBJECTS) $(test_4by4_DEPENDENCIES) $(EXTRA_test_4by4_DEPENDENCIES) 
	@rm -f test_4by4$(EXEEXT)
	$(AM_V_CXXLD)$(test_4by4_LINK) $(test_4by4_OBJECTS) $(test_4by4_LDADD) $(LIBS)

test_cab_es1$(EXEEXT): $(test_cab_es1_OBJECTS) $(test_cab_es1_DEPENDENCIES) $(EXTRA_test_cab_es1_DEPENDENCIES) 
	@rm -f test_cab_es1$(EXEEXT)
	$(AM_V_CXXLD)$(test_cab_es1_LINK) $(test_cab_es1_OBJECTS) $(test_cab_es1_LDADD) $(LIBS)

test_cab_es2$(EXEEXT): $(test_cab_es2_OBJECTS) $(test_cab_es2_DEPENDENCIES) $(EXTRA_test_cab_es2_DEPENDENCIES) 
	@rm -f test_cab_es2$(EXEEXT)
	$(AM_V_CXXLD)$(test_cab_es2_LINK) $(test_cab_es2_OBJECTS) $(test_cab_es2_LDADD) $(LIBS)

test_cab_es4$(EXEEXT): $(test_cab_es4_OBJECTS) $(test_cab_es4_DEPENDENCIES) $(EXTRA_test_cab_es4_DEPENDENCIES) 
	@rm -f test_cab_es4$(EXEEXT)
	$(AM_V_CXXLD)$(test_cab_es4_LINK) $(test_cab_es4_OBJECTS) $(test_cab_es4_LDADD) $(LIBS)

test_cab_es5$(EXEEXT): $(test_cab_es5_OBJECTS) $(test_cab_es5_DEPENDENCIES) $(EXTRA_test_cab_es5_DEPENDENCIES) 
	@rm -f test_cab_es5$(EXEEXT)
	$(AM_V_CXXLD)$(test_cab_es5_LINK) $(test_cab_es5_OBJECTS) $(test_cab_es5_LDADD) $(LIBS)

test_cab_es6$(EXEEXT): $(test_cab_es6_OBJECTS) $(test_cab_es6_DEPENDENCIES) $(EXTRA_test_cab_es6_DEPENDENCIES) 
	@rm -f test_cab_es6$(EXEEXT)
	$(AM_V_CXXLD)$(test_cab_es6_LINK) $(test_cab_es6_OBJECTS) $(test_cab_es6_LDADD) $(LIBS)

test_cab_es9$(EXEEXT): $(test_cab_es9_OBJECTS) $(test_cab_es9_DEPENDENCIES) $(EXTRA_test_cab_es9_DEPENDENCIES) 
	@rm -f test_cab_es9$(EXEEXT)
	$(AM_V_CXXLD)$(test_cab_es9_LINK) $(test_cab_es9_OBJECTS) $(test_cab_es9_LDADD) $(LIBS)

test_cyclicn$(EXEEXT): $(test_cyclicn_OBJECTS) $(test_cyclicn_DEPENDENCIES) $(EXTRA_test_cyclicn_DEPENDENCIES) 
	@rm -f test_cyclicn$(EXEEXT)
	$(AM_V_CXXLD)$(test_cyclicn_LINK) $(test_cyclicn_OBJECTS) $(test_cyclicn_LDADD) $(LIBS)

test_dynamic$(EXEEXT): $(test_dynamic_OBJECTS) $(test_dynamic_DEPENDENCIES) $(EXTRA_test_dynamic_DEPENDENCIES) 
	@rm -f test_dynamic$(EXEEXT)
	$(AM_V_CXXLD)$(test_dynamic_LINK) $(test_dynamic_OBJECTS) $(test_dynamic_LDADD) $(LIBS)

test_f4$(EXEEXT): $(test_f4_OBJECTS) $(test_f4_DEPENDENCIES) $(EXTRA_test_f4_DEPENDENCIES) 
	@rm -f test_f4$(EXEEXT)
	$(AM_V_CXXLD)$(test_f4_LINK) $(test_f4_OBJECTS) $(test_f4_LDADD) $(LIBS)

test_f4_dynamic$(EXEEXT): $(test_f4_dynamic_OBJECTS) $(test_f4_dynamic_DEPENDENCIES) $(EXTRA_test_f4_dynamic_DEPENDENCIES) 
	@rm -f test_f4_dynamic$(EXEEXT)
	$(AM_V_CXXLD)$(test_f4_dynamic_LINK) $(test_f4_dynamic_OBJECTS) $(test_f4_dynamic_LDADD) $(LIBS)

test_glpk_solver$(EXEEXT): $(test_glpk_solver_OBJECTS) $(test_glpk_solver_DEPENDENCIES) $(EXTRA_test_glpk_solver_DEPENDENCIES) 
	@rm -f test_glpk_solver$(EXEEXT)
	$(AM_V_CXXLD)$(test_glpk_solver_LINK) $(test_glpk_solver_OBJECTS) $(test_glpk_solver_LDADD) $(LIBS)

test_gmp$(EXEEXT): $(test_gmp_OBJECTS) $(test_gmp_DEPENDENCIES) $(EXTRA_test_gmp_DEPENDENCIES) 
	@rm -f test_gmp$(EXEEXT)
	$(AM_V_CXXLD)$(test_gmp_LINK) $(test_gmp_OBJECTS) $(test_gmp_LDADD) $(LIBS)

test_hilbert_functions$(EXEEXT): $(test_hilbert_functions_OBJECTS) $(test_hilbert_functions_DEPENDENCIES) $(EXTRA_test_hilbert_functions_DEPENDENCIES) 
	@rm -f test_hilbert_functions$(EXEEXT)
	$(AM_V_CXXLD)$(test_hilbert_functions_LINK) $(test_hilbert_functions_OBJECTS) $(test_hilbert_functions_LDADD) $(LIBS)

test_incremental_betti$(EXEEXT): $(test_incremental_betti_OBJECTS) $(test_incremental_betti_DEPENDENCIES) $(EXTRA_test_incremental_betti_DEPENDENCIES) 
	@rm -f test_incremental_betti$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(test_incremental_betti_OBJECTS) $(test_incremental_betti_LDADD) $(LIBS)

test_initial_analysis$(EXEEXT): $(test_initial_analysis_OBJECTS) $(test_initial_analysis_DEPENDENCIES) $(EXTRA_test_initial_analysis_DEPENDENCIES) 
	@rm -f test_initial_analysis$(EXEEXT)
	$(AM_V_CXXLD)$(test_initial_analysis_LINK) $(test_initial_analysis_OBJECTS) $(test_initial_analysis_LDADD) $(LIBS)

test_monomials$(EXEEXT): $(test_monomials_OBJECTS) $(test_monomials_DEPENDENCIES) $(EXTRA_test_monomials_DEPENDENCIES) 
	@rm -f test_monomials$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(test_monomials_OBJECTS) $(test_monomials_LDADD) $(LIBS)

user_interface$(EXEEXT): $(user_interface_OBJECTS) $(user_interface_DEPENDENCIES) $(EXTRA_user_interface_DEPENDENCIES) 
	@rm -f user_interface$(EXEEXT)
	$(AM_V_CXXLD)$(user_interface_LINK) $(user_interface_OBJECTS) $(user_interface_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/algorithm_buchberger_basic.Po
include ./$(DEPDIR)/algorithm_buchberger_dynamic.Po
include ./$(DEPDIR)/algorithm_buchberger_explorer_serial.Po
include ./$(DEPDIR)/betti.Po
include ./$(DEPDIR)/critical_pair.Po
include ./$(DEPDIR)/dense_univariate_integer_poly.Po
include ./$(DEPDIR)/dense_univariate_rational_poly.Po
include ./$(DEPDIR)/dynamic_engine.Po
include ./$(DEPDIR)/f4_dynamic.Po
include ./$(DEPDIR)/f4_reduction.Po
include ./$(DEPDIR)/fields.Po
include ./$(DEPDIR)/glpk_solver.Po
include ./$(DEPDIR)/hilbert_functions.Po
include ./$(DEPDIR)/indeterminate.Po
include ./$(DEPDIR)/lp_solver.Po
include ./$(DEPDIR)/monomial.Po
include ./$(DEPDIR)/monomial_ideal.Po
include ./$(DEPDIR)/monomial_ordering.Po
include ./$(DEPDIR)/normal_strategy.Po
include ./$(DEPDIR)/particular_orderings.Po
include ./$(DEPDIR)/polynomial.Po
include ./$(DEPDIR)/polynomial_array.Po
include ./$(DEPDIR)/polynomial_double_buffered.Po
include ./$(DEPDIR)/polynomial_geobucket.Po
include ./$(DEPDIR)/polynomial_linked_list.Po
include ./$(DEPDIR)/polynomial_ring.Po
include ./$(DEPDIR)/ppl_solver.Po
include ./$(DEPDIR)/reduction_support.Po
include ./$(DEPDIR)/skeleton.Po
include ./$(DEPDIR)/strategies.Po
include ./$(DEPDIR)/sugar_strategy.Po
include ./$(DEPDIR)/test_4by4.Po
include ./$(DEPDIR)/test_cab_es1.Po
include ./$(DEPDIR)/test_cab_es2.Po
include ./$(DEPDIR)/test_cab_es4.Po
include ./$(DEPDIR)/test_cab_es5.Po
include ./$(DEPDIR)/test_cab_es6.Po
include ./$(DEPDIR)/test_cab_es9.Po
include ./$(DEPDIR)/test_cyclicn.Po
include ./$(DEPDIR)/test_dynamic.Po
include ./$(DEPDIR)/test_f4.Po
include ./$(DEPDIR)/test_f4_dynamic.Po
include ./$(DEPDIR)/test_glpk_solver.Po
include ./$(DEPDIR)/test_gmp.Po
include ./$(DEPDIR)/test_hilbert_functions.Po
include ./$(DEPDIR)/test_incremental_betti.Po
include ./$(DEPDIR)/test_initial_analysis.Po
include ./$(DEPDIR)/test_monomials.Po
include ./$(DEPDIR)/user_interface.Po
include ./$(DEPDIR)/weighted_sugar_strategy.Po

.cpp.o:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
