var searchData=
[
  ['base_5fring',['base_ring',['../group__polygroup.html#ab3e27b16e7da9518ccba7f91969cd88f',1,'Indeterminate::base_ring()'],['../group__polygroup.html#abf1f531c0004bf37874e98eee42dc0f4',1,'Abstract_Polynomial::base_ring()']]],
  ['begin',['begin',['../group__polygroup.html#ad8da27c2d5e41d6e81d15d756eebf868',1,'Abstract_Polynomial::begin()'],['../group__polygroup.html#aaf17fe042545372d6ceb5858f3e3afac',1,'Constant_Polynomial::begin()'],['../group__polygroup.html#a85169b0b1146537bb69127f3c1a866ff',1,'Double_Buffered_Polynomial::begin()'],['../group__polygroup.html#a0c5f05f041e6d2c462d1dcb2bdd39df0',1,'Polynomial_Geobucket::begin()'],['../group__polygroup.html#a32a8c930f367bf556b27e37c5cf0d2e7',1,'Polynomial_Linked_List::begin()']]],
  ['buchberger',['buchberger',['../group___g_b_computation.html#ga37aa7e2fec96fac6c914934a4243f603',1,'buchberger(const list&lt; Abstract_Polynomial *&gt; &amp;F, SPolyCreationFlags method, StrategyFlags strategy, WT_TYPE *strategy_weights):&#160;algorithm_buchberger_basic.cpp'],['../group___g_b_computation.html#ga37aa7e2fec96fac6c914934a4243f603',1,'buchberger(const list&lt; Abstract_Polynomial *&gt; &amp;F, SPolyCreationFlags rep=SPolyCreationFlags::GEOBUCKETS, StrategyFlags strategy=StrategyFlags::SUGAR_STRATEGY, WT_TYPE *strategy_weights=nullptr):&#160;algorithm_buchberger_basic.cpp']]],
  ['buchberger_5fdynamic',['buchberger_dynamic',['../group___g_b_computation.html#ga2c05f4e2ea8b43bb696483469f4cce83',1,'buchberger_dynamic(const list&lt; Abstract_Polynomial *&gt; &amp;F, SPolyCreationFlags method, StrategyFlags strategy, WT_TYPE *strategy_weights, Dynamic_Heuristic heuristic, DynamicSolver solver_type, bool analyze_inputs):&#160;algorithm_buchberger_dynamic.cpp'],['../group___g_b_computation.html#ga2c05f4e2ea8b43bb696483469f4cce83',1,'buchberger_dynamic(const list&lt; Abstract_Polynomial *&gt; &amp;F, SPolyCreationFlags method=SPolyCreationFlags::GEOBUCKETS, StrategyFlags strategy=StrategyFlags::SUGAR_STRATEGY, WT_TYPE *strategy_weights=nullptr, Dynamic_Heuristic heuristic=Dynamic_Heuristic::ORD_HILBERT_THEN_DEG, DynamicSolver solver=SKELETON_SOLVER, bool analyze_inputs=false):&#160;algorithm_buchberger_dynamic.cpp']]],
  ['buchberger_5fexplorer',['buchberger_explorer',['../group___g_b_computation.html#gaaaca5a3659aba7d4b3a41e253dc1a60f',1,'buchberger_explorer(const vector&lt; Abstract_Polynomial *&gt; &amp;F, SPolyCreationFlags method, StrategyFlags strategy, WT_TYPE *strategy_weights, const int comm_id, const int comm_size):&#160;algorithm_buchberger_explorer.cpp'],['../group___g_b_computation.html#gaaaca5a3659aba7d4b3a41e253dc1a60f',1,'buchberger_explorer(const vector&lt; Abstract_Polynomial *&gt; &amp;F, SPolyCreationFlags method=SPolyCreationFlags::GEOBUCKETS, StrategyFlags strategy=StrategyFlags::NORMAL_STRATEGY, WT_TYPE *strategy_weights=nullptr, const int comm_id=0, const int comm_size=1):&#160;algorithm_buchberger_explorer.cpp'],['../group___g_b_computation.html#ga40495dfdaa22897e1dfe33aaaec35429',1,'buchberger_explorer(const list&lt; Abstract_Polynomial *&gt; &amp;F, SPolyCreationFlags method, StrategyFlags strategy, WT_TYPE *strategy_weights, const unsigned number_to_advance):&#160;algorithm_buchberger_explorer_serial.cpp'],['../group___g_b_computation.html#ga40495dfdaa22897e1dfe33aaaec35429',1,'buchberger_explorer(const list&lt; Abstract_Polynomial *&gt; &amp;F, SPolyCreationFlags method=SPolyCreationFlags::GEOBUCKETS, StrategyFlags strategy=StrategyFlags::NORMAL_STRATEGY, WT_TYPE *strategy_weights=nullptr, const unsigned number_to_advance=2):&#160;algorithm_buchberger_explorer_serial.cpp']]],
  ['build_5freducer',['build_reducer',['../group___g_b_computation.html#a385d863722c1e2f9e9769ba27b5cb374',1,'F4_Reduction_Data::build_reducer(unsigned, const Monomial &amp;)'],['../group___g_b_computation.html#aadda8de768e8a8c504979be7425f85ac',1,'F4_Reduction_Data::build_reducer(vector&lt; COEF_TYPE &gt; &amp;buffer, unsigned i)'],['../group___g_b_computation.html#aadda8de768e8a8c504979be7425f85ac',1,'F4_Reduction_Data::build_reducer(vector&lt; COEF_TYPE &gt; &amp;buffer, unsigned i)']]]
];
